#!/bin/bash

# Tutorial: https://extensionworkshop.com/documentation/develop/developing-extensions-for-firefox-for-android/
SERIAL=$(~/Software/adb/platform-tools-latest-linux/platform-tools/adb get-serialno)
echo "$SERIAL"
node_modules/web-ext/bin/web-ext.js run -t firefox-android --adb-bin ~/Software/adb/platform-tools-latest-linux/platform-tools/adb --firefox-apk org.mozilla.firefox --android-device="$SERIAL"
